import argparse

def parse_configure():
    parser = argparse.ArgumentParser(description="explainer")
    parser.add_argument("--dataset", type=str, default="amazon", help="Dataset name")
    parser.add_argument("--batch_size", type=int, default=8, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate")
    parser.add_argument("--weight_decay", type=float, default=1e-6, help="Weight decay")
    parser.add_argument("--epochs", type=int, default=3, help="Number of epochs")
    parser.add_argument("--mode", type=str, default="finetune", help="finetune or generate")
    parser.add_argument("--model_name", type=str, default="llama_8b", help="model name")
    parser.add_argument("--task_name", type=str, default="profile", help="define the task name")
    parser.add_argument("--random", action="store_true", help="randomly initialize the embeddings")
    parser.add_argument("--if_profile", action="store_true", help="use profile")
    parser.add_argument("--enable_wandb", type=str, default=None, help="use enable_wandb")
    parser.add_argument("--user_emb_path", type=str, default="", help="define the task name")
    parser.add_argument("--item_emb_path", type=str, default="", help="define the task name")
    parser.add_argument("--eval_batch_size", type=int, default=5, help="define the task name")
    parser.add_argument("--indice", action="store_true", help="use profile")
    parser.add_argument("--load_name", type=str, default="pure_graph_5", help="use profile")
    parser.add_argument("--token_trainable", action="store_true", help="use profile")
    parser.add_argument("--moe", action="store_true", help="use profile")
    parser.add_argument("--multi_token", type=int, default=0, help="use profile")
    parser.add_argument("--token_dim", type=int, default=768, help="use profile")
    parser.add_argument("--beta", type=float, default=1.0, help="beta")
    parser.add_argument("--clr", type=float, default=0, help="beta")
    parser.add_argument("--type_emb", action="store_true", help="use profile")
    return parser.parse_args()

args = parse_configure()
