; training.set=./dataset/airbnbLondon/train_new.txt
; test.set=./dataset/airbnbLondon/test_new.txt
; social.data=./dataset/airbnbLondon/trust.txt
; training.set=/root/home/SELFRec/dataset/amazon-science/train.txt
; test.set=/root/home/SELFRec/dataset/amazon-science/test.txt
; social.data=/root/home/SELFRec/dataset/amazon-science/trust.txt
; training.set=/root/home/SELFRec/dataset/amazon-beauty/train.txt
; test.set=/root/home/SELFRec/dataset/amazon-beauty/test.txt
; social.data=/root/home/SELFRec/dataset/amazon-beauty/trust.txt
training.set=/root/home/SELFRec/dataset/amazon-software/train.txt
test.set=/root/home/SELFRec/dataset/amazon-software/test.txt
social.data=/root/home/SELFRec/dataset/amazon-software/trust.txt
model.name=MHCN
model.type=graph
item.ranking=-topN 10,20
embedding.size=64
num.max.epoch=500
batch_size=2048
learnRate=0.001
reg.lambda=0.0001
MHCN=-n_layer 2 -ss_rate 0.01
output.setup=-dir ./results/
